version: "3"

services:
  devcontainer:
    build: ./ubuntu
    network_mode: "host"
    command: "-f /dev/null"
    entrypoint: /usr/bin/tail
    tty: true
    user: "${UID}:${GID}"
    cap_add:
      - ALL
    pid: "host"
    volumes:
      - ~/.dotvim:/home/hawtian/.dotvim:ro
      - ~/.config/nvim/:/home/hawtian/.config/nvim:ro

